name: 'Enable Private Repositories'
description: Run Go unit tests on CryptoPirates private repositories.
author: Colin Campbell
inputs:
  repositoryName:
    description: The name of the repository.
    required: true
  gitHubUsername:
    description: A GitHub user's username.
    required: true
  gitHubAccessToken:
    description: A GitHub user's personal access token.
    required: true
  requiresTALib:
    description: Whether or not the package requires the use of TA-Lib.
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
