name: 'Enable Private Repositories'
description: Run Go unit tests on CryptoPirates private repositories.
author: Colin Campbell
inputs:
  gitUsername:
    description: A GitHub user's username.
    required: true
  gitAccessToken:
    description: A GitHub user's personal access token.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
