name: 'Enable Private Repositories'
description: Run Go unit tests on CryptoPirates private repositories.
author: Colin Campbell
inputs:
  gitUsername:
    description: A GitHub user's username.
    required: true
  gitAccessToken:
    description: A GitHub user's personal access token.
    required: true
  requiresTALib:
    description: Whether or not the package requires the use of TA-Lib.
    required: false
    default: false
  requiresLibrdkafka:
    descriptions: Whether or not the package requires the use of librdkafka.
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
