name: Test Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cryptopirates/unit-tests-action@master
      with:
        gitUsername: ${{ secrets.GIT_USERNAME }}
        gitAccessToken: ${{ secrets.GIT_ACCESS_TOKEN }}
        requiresTALib: true
