name: Test Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cryptopirates/unit-tests-action@master
      with:
        repositoryName: unit-tests-action
        username: ${{ secrets.CP_USER }}
        accessToken: ${{ secrets.CP_ACCESS_TOKEN }}
        requiresTALib: true
