name: Unit Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Git configuration
      run: git config --global url."https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Unit Tests
      uses: cryptopirates/unit-tests-action@master
      with:
        gitUsername: ${{ secrets.GIT_USERNAME }}
        gitAccessToken: ${{ secrets.GIT_ACCESS_TOKEN }}
        requiresTALib: true
        requiresLibrdkafka: true
